memeLab/Jandig

src/ARte/core/jinja2/core/exhibit_detail.jinja2

fixed bug where artwork pop-ups would not show in exhibit page

---

src/ARte/users/jinja2/users/components/elements-modal.jinja2
src/ARte/users/static/css/elements-modal.css
src/ARte/users/views.py

Adding artwork view enhancements within the modals, solving issue #251

Modalworks

---

Makefile
makefile.py

To work it is necessary to fill the data in the Makefile and makefile.py file and configure the server that will receive the data.

Backup routine automated

---

src/ARte/users/jinja2/users/components/item-list.jinja2
src/ARte/users/jinja2/users/profile-edit.jinja2

It resolves the issue #238, so that the user does not remove something accidentally.

Confirmation pop-up before deleting something

---

src/ARte/users/jinja2/users/components/item-list.jinja2

Changed the way issue #254 was solved, so that it is implemented in the same way of described in the topic.

Modify the text link to exhibition artwork(s)

---

src/ARte/users/forms.py
src/ARte/users/jinja2/users/components/elements-modal.jinja2
src/ARte/users/jinja2/users/components/item-list.jinja2

The problem was that I was considering that no other format of image other than gif would be used in the application. Now the condition covers the other formats.
closes #292

Fix images being rendered as video

---

src/ARte/users/forms.py

Branch created to fix issue #288.

Warn the user if s/he types a wrong password

---

src/ARte/users/views.py

Branch create to solve the issue #250

Let a curator create an exhibit using any artworks (even if it not yours)

---

src/ARte/core/jinja2/core/collection.jinja2
src/ARte/users/jinja2/users/components/elements-modal.jinja2
src/ARte/users/models.py
src/ARte/users/urls.py
src/ARte/users/views.py

This branch has been created to fix issue #237

Make it possible to see where a element is being used

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/issue_template.md
.github/PULL_REQUEST_TEMPLATE.md

Creation of issues, PR and bug report templates
#324 
* Report bugs, general issues, pull requests templates
* Update contribution guide about branch policies

[REVIEW] Add issues, bugs, PR template and branch policies

---

README.md

Readme fixed.
#335 
* Try to run project
* Check incorrect commands
* Fix readme

Fix readme incorrect instructions

---

docs/vision-document.md

As part of the documentation, this is the vision document about Jandig ARte
#326 
* Fill content about the product

[REVIEW] Create Vision document

---

src/ARte/users/jinja2/users/upload.jinja2
src/ARte/users/static/css/upload.css
src/ARte/users/views.py

Fixing proportions of Mp4 video that were breaking when trying to create art.
#319 
* Get Scale the value of the video or gif to save in the database.
* Preview mp4 or gif in the object form was fixed.
@darmsDD helped me with this issue.

Mp4 video proportions breaking create artwork

---

src/ARte/users/jinja2/users/components/item-list.jinja2

The button for edition, deletion and preview now appears for videos too.
#320 
* Close the tag of video
@shayanealcantara collaborated with this pull request.

Adjust video tag to show buttons

---

src/ARte/core/jinja2/core/exhibit_select.jinja2
src/ARte/core/static/css/exhibit-detail.css

Create a search box on the Exhibition screen to search the exhibition.
#261 
* A search bar has been created
* The dropdown value is filled with the search
@MatheusBlanco helped me with this issue.

[REVIEW] 261 - As an user, I want to start writting a name of an exhibition and see it, so I don't need to find it in a long drop-down menu

---

README.md

Adds GCES team information to the readme.md

[REVIEW] Update Readme.md with GCES team info

---

src/.envs/.dev_deploy
src/.envs/.prod_deploy
src/.envs/.staging_deploy
src/ARte/users/services/email_service.py

Co-authored-by: Welison Almeida <welison.almeida.923@gmail.com>
Moved SMTP credentials to external environment variable
#374 
Added environment variable on files:
* `.dev_deploy`;
* `.prod_deploy`;
* `.staging_deploy`.

[REVIEW] 374 - Move SMTP credentials to external environment variable

---

locale/pt_BR/LC_MESSAGES/django.po
src/ARte/users/jinja2/users/exhibit-create.jinja2

Correction on exhibit URL creation error translation when using special characters.
#378 
* Translation of the error message

[REVIEW] 378 - Exhibit url error translation

---

src/ARte/users/jinja2/users/artwork-create.jinja2
src/ARte/users/jinja2/users/artwork-edit.jinja2
src/ARte/users/jinja2/users/exhibit-create.jinja2
src/ARte/users/jinja2/users/exhibit-edit.jinja2

In some files, I found some numbers in the code that means something in the code, but for new collaborators it may confuse to understand what is happening. I found some of them in the following files
#410 
*  Changed some files to use more semantic meaning to the numbers

[REVIEW] Replace some magic numbers

---

src/ARte/core/jinja2/core/exhibit.jinja2
src/ARte/core/static/js/main.js
src/ARte/core/static/js/pdfGenerator.js
src/ARte/users/jinja2/users/components/artworks-list.jinja2
src/ARte/users/jinja2/users/components/item-list.jinja2
src/ARte/users/jinja2/users/components/moderator-item-list.jinja2
src/ARte/users/jinja2/users/upload.jinja2

Since it's not nice to have debug logs in development branch, I took some of them of so the devTools doens't get stuffed with some debug information 
#407 
* Remove console.logs from jinja files

[Review] #407 - remove console.logs

---

README.md
docker/docker-compose.yml
src/requirements.txt

This pull request update the README to fix the docker-compose command and include windows commands to run the project.
Resolve #329 
* Update README.md to include  operational system windows.

[WIP] 329 - Update Readme Document

---

docs/architecture-document.md
docs/images/plantUML/mtv-architecture-diagram.puml
docs/images/plantUML/package-diagram-logical-view.puml

Improve Architecture Document
Resolve #437
* Reference the Plant UML source code in the doc
* Improve Architectural Representation topic of SAD
* Fix typos

 [REVIEW] 437 - Improve Architecture Document

---

src/ARte/users/jinja2/users/components/userbox.jinja2
src/ARte/users/static/css/signup.css

This pull request update the User Experience of the project, adding a logout button in user profile page and change error message color.
Resolve #440
Resolve #441
* Update color of signup erro message;
* Add logout button in user profile.

440 - Improve signup screen error messages and 441 - Add a 'logout' button in User Profile page 

---

.github/CODE_OF_CONDUCT.md

Code of conduct update for [Contributor Covenant Code of Conduct version 2.0](https://www.contributor-covenant.org/version/2/0/code_of_conduct/).
Fix #290 
* Update the code of conduct.
* Update the contact e-mail.

[REVIEW] 290 - As a developer, I want to find easily an updated code of conduct, so I can read and understand it

---

docker/Dockerfile
run.sh
src/ARte/core/urls.py
src/requirements.txt

This pull request, fixes some issues found when trying to set up the development environment, as described in issue #459.
resolve #459.
*  Removes duplicate dependency;
*  Adds missing import;
*  Add migration task to initialization;

[REVIEW] 459 - Problems setting up the environment

---

src/ARte/core/models.py
src/ARte/core/views.py
src/ARte/users/views.py

Added `.order_by('-id')` in all querysets related to model Artworks
#435 - As a curator, I want the order of the artworks goes from newest to oldest, so I can find content more easily. 
* Add `.order_by('-id')` in all querysets related to model Artworks

[REVIEW] 435 - Change Artworks order to newset to oldest

---

src/ARte/users/jinja2/users/artwork-create.jinja2
src/ARte/users/jinja2/users/artwork-edit.jinja2
src/ARte/users/jinja2/users/login.jinja2
src/ARte/users/jinja2/users/signup.jinja2
src/ARte/users/jinja2/users/upload-marker.jinja2
src/ARte/users/jinja2/users/upload-object.jinja2
src/ARte/users/jinja2/users/upload.jinja2

I added a label to all checkboxes in application forms.
Once the checkbox texts are wrapped with the label tag, clicking on the text triggers its respective checkbox.
#482 Improved usability of checkboxes
* Wrap all checkboxes texts with `label` tag

[REVIEW] #482 - Add label to all checkbox text

---

.github/workflows/ci.yml
Makefile
poetry.lock
pyproject.toml
src/users/services/email_service.py
src/users/tests/test_users.py

A clear and concise description of what was made.
* Add flake8 to project
* Removed some flake8 lint erros

fix: add flake8 to project and fix some lint erros

---

src/core/serializers/objects.py
src/core/tests/test_objects_api.py
src/core/urls.py
src/core/views/objects.py

A clear and concise description of what was made.
* Add Object model viewset
* Add Object model serializer
* Add Object model url
* Add Object model tests

feat: add object viewset, serializer, url and tests

---

src/core/serializers/artworks.py
src/core/tests/test_artworks_api.py
src/core/urls.py
src/core/views/artworks.py

A clear and concise description of what was made.
* Add Artwork model viewset
* Add Artwork model serializer
* Add Artwork model url
* Add Artwork model tests

feat: add artworks viewset, serializer, url and tests

---

src/core/serializers/exhibits.py
src/core/tests/test_exhibits_api.py
src/core/urls.py
src/core/views/exhibits.py

A clear and concise description of what was made.
* Add Exhibit model viewset
* Add Exhibit model serializer
* Add Exhibit model url
* Add Exhibit model tests

feat: add exhibits viewset, serializer, url and tests

---

src/core/jinja2/core/generator.html

Added the viewport meta tag to generator html file.
resolves #478 
* Add meta tag with viewport setting `width=device-width` and  `initial-scale=1`

[REVIEW] 478 - Mobile Usability issues

---

docs/old hotsite/css/style.css
src/users/forms.py

Fixed component styling that was not behaving as expected.
#513

[Review] 513 Component styling fix

---

docs/conf.py
locale/pt_BR/LC_MESSAGES/django.po

Added links to redirect to github repository and  jandig homepage.
#465 
* Added jandig logo to help page
* Added  github repository and jandig homepage to the sidebar of the help page

[Review] Navigation error on "Help" page

---

src/core/static/css/home.css

The login and signup button component is showing incorrect peding behavior which is leaving the text off center.
Login and Sign Up button texts are now centered

Centering button text

---

docs/animacoes-ingles.rst

Remotion of portuguese paragraph
#527

Removendo parágrafo em português

---

src/core/static/css/home.css

The button's CSS was refactored in order to correct the button's anomalous decentralization behavior
#529
* Fix styling of login and singup button component

[REVIEW] Login and Singup component fix 

---

src/core/forms.py
src/core/jinja2/core/exhibit_select.jinja2
src/core/views/views.py

Reverts memeLab/Jandig#596
This merge request does not work on mobile devices, so I'll be reverting it for further work with #601.

Revert "Fix MR 454 conflicts"

---

locale/pt_BR/LC_MESSAGES/django.po
src/users/jinja2/users/edit-object.jinja2
src/users/jinja2/users/upload-object.jinja2

This pull request adds a validation on the objects upload to avoid wrong file formats to be used.
#289 
* Added a validation based on the file format of the file uploaded
* Refactored the Edit object's page to standardize the file handling

[Review] 289 - As an artist, I want to receive a warning when I try to upload the wrong file format, so I can publish the right one.

---

docker-compose.yml
etc/haproxy/haproxy.cfg
src/core/jinja2/core/exhibit.jinja2
src/core/serializers.py
src/core/views/views.py

Created a local haproxy to redirect requests to storage (MinIO) when needed.
Restores CloudFlare cache when using exhibits directly.

Add local reverse proxy to simulate AWS conditions

---

run.sh
src/users/forms.py
src/users/tests/test_signup.py

Usernames now allow up to 20 characters to be used on signup.
Resolves: #706

Allow usernames up to 20 characters
