ARte/pwa/forms.py, ARte/pwa/helpers.py, ARte/pwa/jinja2/pwa/upload.jinja2, ARte/pwa/urls.py, ARte/pwa/views.py
Fix #77 
@pablodiegoss This is how I initially implemented the image upload:
1. simple path `/upload` with a form containing only a file input field (no frontend work done here)
2. Once submitted, file is save at `pwa/static/images` and file name is same as user's file name	
3. if image is successful uploaded - return to index page
4. if not, stay at the upload form
=> Add upload functionality - initial

src/ARte/users/jinja2/users/components/artworks-list.jinja2, src/ARte/users/jinja2/users/components/repository-list.jinja2
This is my solution to issue #262 when I diagnostic a background problem on artwork items selection.
The current behavior is:
Artwork:
Exibition:
All tests passed. I hope you like this upgrade.
=> Adjust highlighting selected items

src/ARte/core/jinja2/core/collection.jinja2, src/ARte/core/urls.py, src/ARte/core/views.py
Fixing issue #202 , collection page now loads 4 exhibits and 8 of each category (artwrok, marker and object). Further items can be accessed in a new page with all the content of a category.
=> Collection page now shows fewer items per category

src/ARte/users/jinja2/users/upload.jinja2
Create button that when clicked opens the page https://jandig.app/generator/.
#327 
* Remove the link on the "here" word from the phase "No Marker files yet? Don't fret! You can get them here."
* Insert button with link.
@devsalula helped with this issue.
=> Create button to redirect marker generator #327 

src/ARte/users/forms.py, src/ARte/users/jinja2/users/exhibit-create.jinja2, src/ARte/users/static/css/label.css
In this Pull Request, logic has been added so that users will receive an error message when they try to input an exhibit URL with special characters, as well as not allowing said exhibit to be registered in the database.
#318 
* Filtered the input to accept only non-special characters
* Added a visual alert so the user will see when the slug is invalid.
@devsalula helped me with this issue.
=> [REVIEW] 318 - slug input for exhibition url

src/ARte/users/jinja2/users/components/elements-modal.jinja2, src/ARte/users/views.py
The modal doesn't display the correct object download link
Issues  242 
* Get image path in downloadElement method
@devsalula helped me with this issue.
-[X] Yes
-[ ]No
=> [REVIEW] 242-Wrong link to download Object

src/ARte/core/jinja2/core/generator.html
Co-authored-by: Saleh Kader <saleh.nazih.dev@gmail.com>
Adding a marker transparency alert on the generator screen..
#278 
* Add marker transparency alert
=> [REVIEW] Adding marker transparency info to generator

src/ARte/users/models.py
Co-authored-by: Shayane Alcantara <shayaneliebe@gmail.com>
The 'xproportion' and 'yproportion' methods were doing an if in case the height and width values were greater than 1. However, if the user entered a value less than 1 in the "Scale" field (eg 0.5) , these two values became less than 1, which caused the bug. To correct the problem, we started to check if the height was greater than the width, and vice versa.
#322 
* Modify xproportion method from Object class
* Modify yproportion method from Object class
* Insert comments explaining xproportion, yproportion, xscale, yscale and fullscale methods from Object class
* Explain operation of scales in Jandig in issue's comments.
=> [REVIEW] Fix get methods for scale and proportion

src/ARte/users/jinja2/users/components/item-list.jinja2
Blocks the editing of objects and artworks there are being used.
#351 
* Adjust if clauses to check if the object or artwork is in use, if in use it cannot be edited.
@shayanealcantara helped with this issue.
=> [REVIEW] - Block the editing of an object and artwork when in use

src/ARte/users/factory.py, src/ARte/users/services/email_service.py, src/ARte/users/services/encrypt_service.py, src/ARte/users/services/user_service.py, src/ARte/users/tests.py, src/ARte/users/urls.py, src/ARte/users/views.py, src/requirements.txt
This Pull Request is focused on improving the implementation of the recover password method, adapting it to clean code and solid.
#365
=> [REVIEW] Refactoring of recover password implementation

src/ARte/users/views.py
Divide  delete_content function into delete_content and  delete_content_Moderator to separate the deletion of a normal user and a moderator;
#360 
I did not know how to test moderator permissions, so before accepting this pull request it is necessary to test if the moderator delete still works. I would appreciate if someone told me how to test as moderator.
=> [WIP] Separate delete content into delete_content and delete_content_Moderator

src/ARte/users/jinja2/users/edit-object.jinja2, src/ARte/users/jinja2/users/upload.jinja2
Uploading and editing a object was throwing a error when the scale was given with a comma. I added a replace on the updateValues method that replaces every comma with a dot, in case its given. In case the scale its not given with comma, it doesn't give any error. 
#368 - Index-error
*  On the ARte/users/jinja2/users/upload.jinja2 file, updated the updateValues function to replace the comma with a dot.
* On the ARte/users/jinja2/users/edit-object.jinja2 file, updated the updateValues function to replace the comma with a dot.
=> [Review] 368-index-error

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Add new issue template to feature request under `.github/ISSUE_TEMPLATE` folder.
Resolves: #375
* The issue template is based on other templates from open source projects.
=> [REVIEW] 375 - Add new issue template to feature request

locale/pt_BR/LC_MESSAGES/django.po, src/ARte/users/jinja2/users/artwork-edit.jinja2, src/ARte/users/jinja2/users/exhibit-edit.jinja2, src/ARte/users/views.py
Co-authored-by: gabrieldvpereira  <gdavi.gd@gmail.com>
This pul request creates an editing page for the following actions: 
- Edit an Artwork
- Edit an exhibition
Before this change, those actions were using the creation page for both create and edit. 
#307 
* Create a page for editing Artwork
* Create a page for editing Exhibition
* Add translations on jdango.po file for the new pages
=> [REVIEW] 307 - Creation edition page of artwork.

src/ARte/users/models.py
Co-authored-by: ZarathosDeath <nando_rhapsody@hotmail.com>
Objects titles now are showing as asked on Profile and Artwork tabs
Resolves: #392 
Added __str__ method on the classes that didn't have (Artwork and Profile)
-
=> [REVIEW] 392-titles-django-admin

src/ARte/users/tests.py
The variable now is being defined before used on tests.py
#396 
* Switched the order from lines on tests.py file
##Screenshots
=> [REVIEW] 396 - response used before defined

src/ARte/core/jinja2/core/generator.html, src/ARte/core/static/css/generator.css
The input that takes the user files was accepting all types of file. We limited it to accept only images so the user doesn't submit a file with a wrong format. We also added a cursor pointer to the buttons of the page to improve user experience. 
#418 
* added accept="image/* to the input that takes the user files
* added a cursor:pointer css property to all buttons of the page
=> [REVIEW] Limit input for generator page

src/ARte/users/jinja2/users/upload.jinja2
When creating a new artwork or object, uploading a new image was generating more than one preview even though only one is saved. Also, there was no way to remove a preview selected. 
#420 
* When uploading a new file, we checked if the dom already has a preview rendered, If so, we remove the old preview and add a new one
* We added a close icon that remove the preview selected from the screen
*
=> [REVIEW] Image preview on file upload

.github/ISSUE_TEMPLATE/refactoring.md
Add new issue template to refactoring proposals in the Jandig source code.
Resolve #391.
* Add `refactoring.md` file to `.github/ISSUE_TEMPLATES` folder;
* Add issue template to refactoring proposal to this repository.
=> [REVIEW] 391 - Issue template to refactoring proposal

SECURITY.md
Creation of security policy of the project. In this document we describe how to relate vulnerabilities issues and Jandig's point of view on users security.
Resolves #432 
* Creation of Security Policy document.
=> [REVIEW] #432 - Create Security Policy

src/ARte/users/jinja2/users/components/object-position.jinja2
We've searched the code together and found and fixed the problem about the two words by removing them from the objetc-position.jinja2 file. However, the blank space was actually that we couldn't see a square in the page, which was also fixed.
Resolve #429 
* Remove both undesired words
* Fix blank space
=> [REVIEW] 429 - Undesired words and blank space

docs/fix-code-smells.md, etc/scripts/compilemessages.py, locustfile.py, makefile.py, src/ARte/config/jinja2.py, src/ARte/config/settings.py, src/ARte/config/wait_db.py, src/ARte/core/models.py, src/ARte/core/urls.py, src/ARte/core/views_s/home.py, src/ARte/users/factory.py, src/ARte/users/forms.py, src/ARte/users/models.py, src/ARte/users/services/email_service.py, src/ARte/users/services/encrypt_service.py, src/ARte/users/services/user_service.py, src/ARte/users/urls.py, src/ARte/users/views.py, tasks.py
Correction of Prospector errors executed under Jandig's code. You can see the full tool log [here](https://github.com/FGA-GCES/Jandig/blob/4aced60b0504660a5967b13470a3997519f7b4ca/prospector.txt).
Resolve [#445](https://github.com/memeLab/Jandig/issues/445)
* Fix user view file code violations
* Fix user urls file code violations
* Fix tasks file code violations
* Fix forms file code violations
* Fix encrypt service file code violations
* Fix user service file code violations
* Fix forms file code violations
* Fix models file code violation
* Fix email_service file code violations
* Fix urls file code violations
* Fix home file code violations
* Fix factory file code violation
* Fix settings file code violation
* Fix wait_db file code violation
* Fix locustfile file code violation
* Fix …
=> [REVIEW] 445 - Fix prospector errors

src/ARte/users/forms.py, src/ARte/users/views.py
I found the bug that was generating the TypeError described in issue #466.
Apparently someone was confusing the `owner` and `author` fields and was using the `profile` object for the form, since the form only supports the `author` textual field.
The solution, [according to the Django documentation](https://docs.djangoproject.com/en/3.2/topics/forms/modelforms/#the-save-method), is to first create the object and then associate the created object with the logged in user.
#466 - Create a object results in a TypeError 
* Minor change to how forms are saved in the `upload_elements` function
=> [REVIEW] 466 - Fix created object owner definition

src/ARte/users/jinja2/users/exhibit-create.jinja2
While I was populating the development environment, I noticed that the form for creating an exhibition asks to select artworks, but since there was none, it was a meaningless form.
I added a condition in the form code to redirect the user to the artworks form in scenarios where there are no artworks.
| Before | After |
| :-: | :-: |
| <img src="https://user-images.githubusercontent.com/31013187/198388323-4c5cb7e5-f1f0-445a-90d0-441e3638059f.png" width="800"> | <img src="https://user-images.githubusercontent.com/31013187/198388854-7896852d-1cf5-4752-a4e6-6ee7204a183d.png" width="800"> |
=> [REVIEW] - Add link to create an artwork when there is no artwork

docs/real_docs/development-server.md, poetry.lock, pyproject.toml, run.sh, src/.envs/.example, src/ARte/config/settings.py, src/ARte/core/jinja2/core/collection.jinja2, tasks.py
The whitenoise lib was an old way of serving static files in the project, this was later replaced by MINIO that uses the same structure as an AWS S3 bucket. However the URL protocol for localhosts used to retrieve statics on MINIO was updated and didn't work.
- Fixed MINIO variable for URL protocol
- Removed all tasks, scripts, requirements and documentation about the whitenoise lib
- Fixed a redirect to the All Markers page
* Task 2
=> Remove the whitenoise lib from the project

src/config/test_settings.py, src/core/serializers/artworks.py, src/core/serializers/objects.py, src/core/tests/test_artworks_api.py, src/core/tests/test_exhibits_api.py, src/core/urls.py
Fix linter warning  to pass through pipeline 
memeLab#499
- [ x] Yes
=> [REVIEW] 499 - Flake8 linter

src/users/forms.py
The pull request changes the function used to get the username/email on the login page
#428 
* Changed the function `self.data.get("username")` to `self.cleaned_data.get("username")`
=> [Review] 428 - no login error message when there's a space in the field

locale/pt_BR/LC_MESSAGES/django.po
A translation from English to Portuguese of the missing points on the login screen was carried out.
#515
* Login screen translation
=> [Review] 515 - Completing login screen translation

locale/en_US/LC_MESSAGES/django.po
A translation from Portuguese to English of the missing points on the community screen was carried out.
#523
* Adding translation Tag in the community page
=> [REVIEW] 523 - Community page translation

Makefile, locale/en_US/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, src/core/jinja2/core/community.jinja2, tasks.py
Updated the community page translation to follow our gettext structure
Resolves: #523 
* Added the gettext function to community.jinja2 file
* Moved translated text from en_US to pt_BR
=> Translate community page

locale/pt_BR/LC_MESSAGES/django.po, src/users/forms.py, src/users/jinja2/users/exhibit-create.jinja2
Added form validation and auto modal pop up when there is an error
#367 
* Added form validation
* Added  function to suto show modal when there is an error
=> [REVIEW] Creating exhibit with repeated name crashes the frontend

src/core/admin.py, src/core/models.py, src/users/admin.py, src/users/jinja2/users/components/elements-modal.jinja2, src/users/jinja2/users/components/item-list.jinja2
Improve Object and Markers django admin pages, enabling the analysis of usage by number of artworks and exhibits, while also including a preview of the respective content
* Created custom Object admin page
* Created custom Marker admin page
* Fixed video previews on collection and modal pages
=> Improve Object and Marker admin pages

src/core/admin.py, src/core/models.py, src/core/tests/test_bot_protection.py, src/core/views/views.py, src/users/models.py, src/users/views.py
Updated the artwork and exhibit admin pages, for easier visualization and analysis of data.
* Fixed N+1 queries on Collection and See All pages
* Created new Artwork admin page
* Created new Exhibit admin page
* Improved performance on all core admin pages
=> Update Artwork and Exhibit admin pages

.github/workflows/PipelineRC.yml, Makefile, etc/haproxy/haproxy.cfg, pyproject.toml, src/config/settings.py, src/config/test_settings.py, src/core/tests/factory.py, src/core/tests/test_exhibits_api.py, src/core/views/viewsets.py, src/users/admin.py, src/users/models.py, src/users/tests/factory.py
Enable searching in the Exhibit API by User ID or Name, using query parameters "search" or "owner".
`/api/v1/exhibits/?owner=2`
`/api/v1/exhibits/?search=longa vida`
`/api/v1/exhibits/?owner=1&search=teste`
=> Enable search in exhibit api

.github/workflows/Linter.yml, Makefile, pyproject.toml, src/config/settings.py, src/config/test_settings.py, src/config/urls.py, src/core/tests/test_exhibits_api.py, src/core/urls.py, src/users/admin.py, src/users/models.py, src/users/serializers.py, src/users/tests/test_auth_api.py, src/users/tests/test_profile_api.py, src/users/viewsets.py, uv.lock
Created API for Profiles and Authentication endpoints.
`/api/v1/profiles/`
`/api/v1/profiles/?user=<id>`
`/api/v1/auth/login`
`/api/v1/auth/verify`
`/api/v1/auth/refresh`
=> Add API for user logins with simple jwt

pyproject.toml, src/config/settings.py, src/core/tests/test_artworks_api.py, src/core/tests/test_related_content_view.py, src/core/urls.py, src/core/views/views.py, src/users/jinja2/users/components/elements-modal.jinja2, src/users/urls.py, src/users/views.py
Related content page was raising exceptions after the last performance refactors. This PR fixes the errors and creates unit tests to ensure this feature works.
* Fixed IDs on modal pages
* Fixed related content pages
* Improved performance of queries on related content pages
* Created tests for the related_content view
* Moved related_content view from app users to core
=> Fix related content page

.github/workflows/PipelineRC.yml, pyproject.toml, src/core/jinja2/core/collection.jinja2, src/core/models.py, src/core/tests/factory.py, src/core/tests/test_html_thumbnail_generators.py, src/users/jinja2/users/components/elements-modal.jinja2, src/users/jinja2/users/components/item-list.jinja2, src/users/views.py, uv.lock
Moved business logic from HTML templating with Jinja2 to Python
* Replaced all jinja ifs on item-list component with direct python methods
* Fixed redirect on see_all page
* Fixed tagged images release
* Fixed elements modal for videos
* Fixed slow query on create exhibit endpoint
=> Generate html with Python
